## Start and prep

In [1]:
# we will use Kaggle dataset from here:
# https://www.kaggle.com/datasets/blastchar/telco-customer-churn
# code and video from here:
# https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/03-classification/01-churn-project.md
# notebook 
# https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/03-classification/notebook.ipynb
# dataset for download
# https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv

# Data preparation

# Download the data, read it with pandas
# Look at the data
# Make column names and values look uniform
# Check if all the columns read correctly
# Check if the churn variable needs any preparation
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'


In [3]:
# run once to download the dataset
# !wget $data -O data-week-3.csv 

In [4]:
df = pd.read_csv('data-week-3.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

## Data cleaning part

In [5]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [6]:
df.head().T # nice trick to see all colums ))

0             1               2  \
customerid              7590-vhveg    5575-gnvde      3668-qpybk   
gender                      female          male            male   
seniorcitizen                    0             0               0   
partner                        yes            no              no   
dependents                      no            no              no   
tenure                           1            34               2   
phoneservice                    no           yes             yes   
multiplelines     no_phone_service            no              no   
internetservice                dsl           dsl             dsl   
onlinesecurity                  no           yes             yes   
onlinebackup                   yes            no             yes   
deviceprotection                no           yes              no   
techsupport                     no            no              no   
streamingtv                     no            no              no   
streamingmovies                 no            no              no   
contract            month-to-month      one_year  month-to-month   
paperlessbilling               yes            no             yes   
paymentmethod     electronic_check  mailed_check    mailed_check   
monthlycharges               29.85         56.95           53.85   
totalcharges                 29.85        1889.5          108.15   
churn                           no            no             yes   

                                          3                 4  
customerid                       7795-cfocw        9237-hqitu  
gender                                 male            female  
seniorcitizen                             0                 0  
partner                                  no                no  
dependents                               no                no  
tenure                                   45                 2  
phoneservice                             no               yes  
multiplelines              no_phone_service                no  
internetservice                         dsl       fiber_optic  
onlinesecurity                          yes                no  
onlinebackup                             no                no  
deviceprotection                        yes                no  
techsupport                             yes                no  
streamingtv                              no                no  
streamingmovies                          no                no  
contract                           one_year    month-to-month  
paperlessbilling                         no               yes  
paymentmethod     bank_transfer_(automatic)  electronic_check  
monthlycharges                         42.3              70.7  
totalcharges                        1840.75            151.65  
churn                                    no               yes

In [7]:
# df.dtypes # totalcharges  object - it should be a number! Fill missing values with zeroes...
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce') # convedrting to numbers and replace "-" with NaN

In [8]:
df.totalcharges = df.totalcharges.fillna(0) # fill NaN with zeroes

In [9]:
# df.totalcharges.isnull().sum() # np.int64(0) - now it is OK - no NaN here, only digits
# df.dtypes # totalcharges float64 - all good!
# but churn is the onject still - churn  object - it has yes/no text marks
# df.churn
df.churn = (df.churn == 'yes').astype(int) 

In [10]:
# df.churn # now all looks good -we converted yes to 1 and no to 0

## Setting up the validation framework using Scikit-Learn

In [11]:
# to split dataset automatically we will use scikit-learn
from sklearn.model_selection import train_test_split

In [12]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [13]:
# lets see how skl split our dataset
len(df_train), len(df_val), len(df_test) # looks good - (4225, 1409, 1409)

(4225, 1409, 1409)

In [14]:
# we need to reset index in each split for simplicity
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [15]:
# and remove label we predict - so our model will not accidentally look at it
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

del df_train['churn']
del df_val['churn']
del df_test['churn']

In [16]:
# offtopic - what if I forgot what train_test_split function is doing? Built-in help:
# train_test_split?

## EDA

In [17]:
# We have to
# -- Check missing values
# -- Look at the target variable (churn)
# -- Look at numerical and categorical variables

df_full_train = df_full_train.reset_index(drop=True)

In [18]:
# df_full_train.isnull().sum() # all good - zeroes everywhere - no missing values ))

# we have not deleted our label from full_train - so we can have a look at stats:
df_full_train.churn.value_counts(normalize=True)

# churn - using only df_full_train.churn.value_counts()
# 0    4113 - customers stayed - 73%
# 1    1521 - churned customers - 26%
# churn - using df_full_train.churn.value_counts(normalize=True)
# 0    0.730032
# 1    0.269968

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [19]:
global_churn = df_full_train.churn.mean() # np.float64(0.26996805111821087)
global_churn
# this is called CHURN RATE = 0.2699... or 27% in our case...
# mean works here because churn variable is binary - consists of 1 and 0
# churned customers are marked by 1 in our case

np.float64(0.26996805111821087)

In [20]:
# we have only 3 numeric variables, rest is categorical
numerical = ['tenure', 'monthlycharges', 'totalcharges']
# df_full_train.dtypes
# categorical = [c for c in list(df_full_train.columns) if c not in numerical]
# categorical

# on video it was done manually ))))
# df_full_train.columns
categorical = [ 'gender', 'seniorcitizen', 'partner', 'dependents',
        'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']
# categorical

In [21]:
# how many values each categorical variable has:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

## Feature importance for categorical features

In [22]:
# Idea is to look at churn rate in different groups - to see which categorical variable can predict it

# Feature importance: Churn rate and risk ratio
# Feature importance analysis (part of EDA) - identifying which features affect our target variable

# -- Churn rate
# -- Risk ratio
# -- Mutual information - later

# for example gender does not predict churn:
df_full_train[df_full_train.gender == 'female'].churn.mean()
# np.float64(0.27682403433476394) - roughly the same as in the parent group

np.float64(0.27682403433476394)

In [23]:
# we can repeat the same analysis for other categorical variables
df_full_train.partner.value_counts()

partner
no     2932
yes    2702
Name: count, dtype: int64

In [24]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean() # 20% - np.float64(0.20503330866025166)
churn_partner

np.float64(0.20503330866025166)

In [25]:
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean() # 33% - np.float64(0.3298090040927694)
churn_no_partner
# churn rate is bigger but not sure if it is statistically significant?

np.float64(0.3298090040927694)

In [26]:
# risk ratios - our partner/no partner categorical variables explains ~20% of churn:
churn_partner / global_churn # less by 24% in group who lives with partner
# np.float64(0.7594724924338315)

np.float64(0.7594724924338315)

In [27]:
churn_no_partner / global_churn # churn risk is higher by ~22% in a no partner people group
# np.float64(1.2216593879412643)

np.float64(1.2216593879412643)

In [28]:
# risk analysis code in SQL:
# SELECT
#     gender,
#     AVG(churn),
#     AVG(churn) - global_churn AS diff,
#     AVG(churn) / global_churn AS risk
# FROM
#     data
# GROUP BY
#     gender;


# same code in Pandas to analyse risk ratios of every categorical feature
from IPython.display import display

for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()


gender


mean  count      diff      risk
gender                                     
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980



seniorcitizen


mean  count      diff      risk
seniorcitizen                                     
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208



partner


mean  count      diff      risk
partner                                     
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472



dependents


mean  count      diff      risk
dependents                                     
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651



phoneservice


mean  count      diff      risk
phoneservice                                     
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412



multiplelines


mean  count      diff      risk
multiplelines                                        
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948



internetservice


mean  count      diff      risk
internetservice                                     
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201



onlinesecurity


mean  count      diff      risk
onlinesecurity                                          
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570



onlinebackup


mean  count      diff      risk
onlinebackup                                            
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660



deviceprotection


mean  count      diff      risk
deviceprotection                                        
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480



techsupport


mean  count      diff      risk
techsupport                                             
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390



streamingtv


mean  count      diff      risk
streamingtv                                             
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328



streamingmovies


mean  count      diff      risk
streamingmovies                                         
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182



contract


mean  count      diff      risk
contract                                           
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730



paperlessbilling


mean  count      diff      risk
paperlessbilling                                     
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560



paymentmethod


mean  count      diff      risk
paymentmethod                                                 
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

## Feature importance - mutual information

In [29]:
# mutual information - how much we can explain variations of one variable by observing another
# it is kinda similar to correlation coefficient - but for categorical features ...

# in practice skl has it:

from sklearn.metrics import mutual_info_score 

In [30]:
mutual_info_score(df_full_train.churn, df_full_train.contract) 
# people with 2yr contract has lowest churn risk rate of 10% only - see above in SQL function printout
# 0.0983203874041556 -> ~10%

0.0983203874041556

In [31]:
mutual_info_score(df_full_train.gender, df_full_train.churn)
# 0.00011 - practically zero - gender and churn are NOT correlated

0.0001174846211139946

In [32]:
# lets put it into a function - 

def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.churn)

In [33]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending=False)
# to make sure we see biggest correlations with churn first:
# contract            0.098320
# onlinesecurity      0.063085
# techsupport         0.061032
# internetservice     0.055868
# onlinebackup        0.046923
# deviceprotection    0.043453
# paymentmethod       0.043210
# -- so we get RELATIVE IMPORTANCE of categorical features --

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

## Feature importance: Correlation

In [34]:
# Similar idea but for numerical columns

# Correlation coefficient - https://en.wikipedia.org/wiki/Pearson_correlation_coefficient

df_full_train[numerical].corrwith(df_full_train.churn)
# tenure           -0.351885 - longer the customer stays less like ly she/he churns
# monthlycharges    0.196805 - more monthly charges - more likely customer will churn
# totalcharges     -0.196353 - people who pay more aand use services more prob are happy customers - less likely to churn
# more they pay in total - less they churn
# and more they stay - less they churn too

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

## One-hot encoding

In [35]:
# we use skl too this time
from sklearn.feature_extraction import DictVectorizer


In [37]:
# playing with 1 - hot encoding - create dict first

df_train[['gender', 'contract']].iloc[:10]

gender        contract
0  female        two_year
1    male  month-to-month
2  female  month-to-month
3  female  month-to-month
4  female        two_year
5    male  month-to-month
6    male  month-to-month
7  female  month-to-month
8  female        two_year
9  female  month-to-month

In [41]:
dicts = df_train[['gender', 'contract']].iloc[:10].to_dict(orient='records')
dicts

[{'gender': 'female', 'contract': 'two_year'},
 {'gender': 'male', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'two_year'},
 {'gender': 'male', 'contract': 'month-to-month'},
 {'gender': 'male', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'two_year'},
 {'gender': 'female', 'contract': 'month-to-month'}]

In [45]:
dv = DictVectorizer(sparse=False)
dv

DictVectorizer(sparse=False)

In [46]:
dv.fit(dicts) # take a dictionary and turn it into a vector

DictVectorizer(sparse=False)

In [47]:
dv.transform(dicts) # produce sparse 1-hot vectors
# Please note - as we had only monthly and 2yr contracts we have only 2 columns for contract type, not 3

array([[0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [53]:
dicts = df_train[['gender', 'contract']].iloc[:100].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
dv.fit(dicts)
dv.transform(dicts)[:3] # to show only 3 rows, not 100 ))
# now all 5 columns are present!!!
# array([[0., 0., 1., 1., 0.],
#        [1., 0., 0., 0., 1.],...

array([[0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [55]:
dv.get_feature_names_out()
# array(['contract=month-to-month', 'contract=one_year',
#       'contract=two_year', 'gender=female', 'gender=male'], dtype=object)
# first line [0., 0., 1., 1., 0.] is in fact {'gender': 'female', 'contract': 'two_year'}

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'gender=female', 'gender=male'], dtype=object)

In [56]:
# DictVectorizer is smart enough to leave numerical variables as it is:

dicts = df_train[['gender', 'contract', 'tenure']].iloc[:100].to_dict(orient='records')
dv = DictVectorizer(sparse=False)
dv.fit(dicts)
dv.transform(dicts)[:3]
# shows renure as scalar column - so numeric variable is safe here
# array([[ 0.,  0.,  1.,  1.,  0., 72.],
#        [ 1.,  0.,  0.,  0.,  1., 10.],
#        [ 1.,  0.,  0.,  1.,  0.,  5.]])


array([[ 0.,  0.,  1.,  1.,  0., 72.],
       [ 1.,  0.,  0.,  0.,  1., 10.],
       [ 1.,  0.,  0.,  1.,  0.,  5.]])

In [57]:
dv.get_feature_names_out()
# shows tenure as last column - our numeric variable, rest - transformed categorical columns to 1-hot encoding
# array(['contract=month-to-month', 'contract=one_year',
#        'contract=two_year', 'gender=female', 'gender=male', 'tenure'],
#       dtype=object)


array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'gender=female', 'gender=male', 'tenure'],
      dtype=object)

In [70]:
# finally fit and transform train and val datasets by 1-hot encoding
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict) # WE USE ONLY TRANSFORM IN VAL DATASET - DO NOT FIT THERE!!!
# fit_transform is the same as dv.fit and dv.transform

In [64]:
# CHECK 1
categorical, numerical # to check ourselves if we have our col names still correct

(['gender',
  'seniorcitizen',
  'partner',
  'dependents',
  'phoneservice',
  'multiplelines',
  'internetservice',
  'onlinesecurity',
  'onlinebackup',
  'deviceprotection',
  'techsupport',
  'streamingtv',
  'streamingmovies',
  'contract',
  'paperlessbilling',
  'paymentmethod'],
 ['tenure', 'monthlycharges', 'totalcharges'])

In [71]:
# CHECK 2
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',

In [72]:
# CHECK 3
list(X_val[0]) # 3 numerical cols and many 1-hot encoded categorical...

[np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(70.85),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(0.0),
 np.float64(1.0),
 np.float64(71.0),
 np.float64(4973.4)]

In [75]:
# CHECK 4
X_train.shape, X_val.shape # ((4225, 45), (1409, 45))

((4225, 45), (1409, 45))

## Logistic regression