In [42]:
# starts at https://www.youtube.com/watch?v=Qa0-jYtRdbY
# and contunues to lin alg and Pandas
import numpy as np
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Create simple arrays

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [46]:
# from python list
l = [1, 2, 3, 4, 5, 6, 10]
a = np.array(l)
a

array([ 1,  2,  3,  4,  5,  6, 10])

In [47]:
int(a[3]) # accessing elements by indices

4

In [48]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [49]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

In [50]:
n = np.zeros((5, 3)) # same way it can create arrays from multi-dimensional python lists...

In [51]:
# adressing row
n[1] = [1, 2, 3]
n

array([[0., 0., 0.],
       [1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# adressing column using : operator
n[:, 2] = [10]*5
n

array([[ 0.,  0., 10.],
       [ 1.,  2., 10.],
       [ 0.,  0., 10.],
       [ 0.,  0., 10.],
       [ 0.,  0., 10.]])

## Randomly generated arrays and random seeds

In [53]:
# if we don't need the seed - we get a new array every time
random_different_values = np.random.rand(5, 2)
random_different_values 
# array([[0.20303549, 0.49645129],
#        [0.98002669, 0.31447288],
#        [0.72151985, 0.1577254 ],
#        [0.67189464, 0.64356604],
#        [0.71482408, 0.81511062]])

# array([[0.18126911, 0.94628129],
#        [0.32282185, 0.18224532],
#        [0.28034724, 0.43799104],
#        [0.2495647 , 0.0891415 ],
#        [0.00137409, 0.93752768]])

# and so on - different each time

array([[0.81413841, 0.94809042],
       [0.82288464, 0.51513912],
       [0.22099815, 0.74663141],
       [0.43153777, 0.88830375],
       [0.9411933 , 0.50301225]])

In [54]:
# But if we set up a seed we will get the same results all the time
np.random.seed(2)
similar = np.random.rand(5, 2)
similar # [0.4359949 , 0.02592623] - like in video:
# https://www.youtube.com/watch?v=Qa0-jYtRdbY

# array([[0.4359949 , 0.02592623],
#        [0.54966248, 0.43532239],
#        [0.4203678 , 0.33033482],
#        [0.20464863, 0.61927097],
#        [0.29965467, 0.26682728]])

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [55]:
# np.random.randn - samples from n - normal distribution

# numpy allows easy multiplication and any other ariphmetics:
5 * similar # every element is multiplied by 5

array([[2.17997451, 0.12963116],
       [2.74831239, 2.17661196],
       [2.10183901, 1.65167411],
       [1.02324317, 3.09635483],
       [1.49827337, 1.33413638]])

In [56]:
# how to generate integers, not floats
np.random.seed(2)
sim_int = np.random.randint(low=0, high=100, size=(5, 2))
sim_int

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [57]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [58]:
# we can add without loops:
a + 1

array([1, 2, 3, 4, 5])

In [59]:
10 + a * 2 # and perform any ariphmetics freely...

array([10, 12, 14, 16, 18])

## Comparison

In [60]:
a

array([0, 1, 2, 3, 4])

In [61]:
a >= 2

array([False, False,  True,  True,  True])

In [62]:
a[a >= 2] # - selecting elements which are greater than 2 without loops

array([2, 3, 4])

## Summarising operations

In [63]:
a.min()

np.int64(0)

In [64]:
a.mean()

np.float64(2.0)

In [65]:
a.sum()

np.int64(10)

## Linear algebra

In [66]:
u = np.random.randint(10, size=10)
len(u)

10

In [67]:
u

array([5, 4, 4, 5, 7, 3, 6, 4, 3, 7])

In [68]:
v = np.random.randint(10, size=10)
v.shape #[0]

(10,)

In [74]:
v

array([6, 1, 3, 5, 8, 4, 6, 3, 9, 2])

In [72]:
# how to multiply vectors
def vec_multiply(u, v):
    assert u.shape[0] == v.shape[0] # to make sure u and v have same dimenson
    
    n = u.shape[0] # esseltially len of u or v
    m = 0 # our sum of multiplication products
    
    for i in range(n):
        m += u[i]*v[i]

    return int(m)

In [73]:
product = vec_multiply(u, v)
product

228

In [71]:
#vec_multiply(a, v) # AssertionError 