In [1]:
# starts at https://www.youtube.com/watch?v=Qa0-jYtRdbY
# and contunues to lin alg and Pandas
import numpy as np
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Create simple arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
# from python list
l = [1, 2, 3, 4, 5, 6, 10]
a = np.array(l)
a

array([ 1,  2,  3,  4,  5,  6, 10])

In [6]:
int(a[3]) # accessing elements by indices

4

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

In [9]:
n = np.zeros((5, 3)) # same way it can create arrays from multi-dimensional python lists...

In [10]:
# adressing row
n[1] = [1, 2, 3]
n

array([[0., 0., 0.],
       [1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# adressing column using : operator
n[:, 2] = [10]*5
n

array([[ 0.,  0., 10.],
       [ 1.,  2., 10.],
       [ 0.,  0., 10.],
       [ 0.,  0., 10.],
       [ 0.,  0., 10.]])

## Randomly generated arrays and random seeds

In [12]:
# if we don't need the seed - we get a new array every time
random_different_values = np.random.rand(5, 2)
random_different_values 
# array([[0.20303549, 0.49645129],
#        [0.98002669, 0.31447288],
#        [0.72151985, 0.1577254 ],
#        [0.67189464, 0.64356604],
#        [0.71482408, 0.81511062]])

# array([[0.18126911, 0.94628129],
#        [0.32282185, 0.18224532],
#        [0.28034724, 0.43799104],
#        [0.2495647 , 0.0891415 ],
#        [0.00137409, 0.93752768]])

# and so on - different each time

array([[0.23553201, 0.86687078],
       [0.10623929, 0.4054606 ],
       [0.91154436, 0.83412218],
       [0.09671484, 0.10364579],
       [0.94899563, 0.32377702]])

In [13]:
# But if we set up a seed we will get the same results all the time
np.random.seed(2)
similar = np.random.rand(5, 2)
similar # [0.4359949 , 0.02592623] - like in video:
# https://www.youtube.com/watch?v=Qa0-jYtRdbY

# array([[0.4359949 , 0.02592623],
#        [0.54966248, 0.43532239],
#        [0.4203678 , 0.33033482],
#        [0.20464863, 0.61927097],
#        [0.29965467, 0.26682728]])

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [14]:
# np.random.randn - samples from n - normal distribution

# numpy allows easy multiplication and any other ariphmetics:
5 * similar # every element is multiplied by 5

array([[2.17997451, 0.12963116],
       [2.74831239, 2.17661196],
       [2.10183901, 1.65167411],
       [1.02324317, 3.09635483],
       [1.49827337, 1.33413638]])

In [15]:
# how to generate integers, not floats
np.random.seed(2)
sim_int = np.random.randint(low=0, high=100, size=(5, 2))
sim_int

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [16]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
# we can add without loops:
a + 1

array([1, 2, 3, 4, 5])

In [18]:
10 + a * 2 # and perform any ariphmetics freely...

array([10, 12, 14, 16, 18])

## Comparison

In [19]:
a

array([0, 1, 2, 3, 4])

In [20]:
a >= 2

array([False, False,  True,  True,  True])

In [21]:
a[a >= 2] # - selecting elements which are greater than 2 without loops

array([2, 3, 4])

## Summarising operations

In [22]:
a.min()

np.int64(0)

In [23]:
a.mean()

np.float64(2.0)

In [24]:
a.sum()

np.int64(10)

## Linear algebra

In [25]:
u = np.random.randint(10, size=10)
len(u)

10

In [26]:
u

array([5, 4, 4, 5, 7, 3, 6, 4, 3, 7])

In [27]:
v = np.random.randint(10, size=10)
v.shape #[0]

(10,)

In [28]:
v

array([6, 1, 3, 5, 8, 4, 6, 3, 9, 2])

In [29]:
# how to multiply vectors
def vec_multiply(u, v):
    assert u.shape[0] == v.shape[0] # to make sure u and v have same dimenson
    
    n = u.shape[0] # esseltially len of u or v
    m = 0 # our sum of multiplication products
    
    for i in range(n):
        m += u[i]*v[i]

    return m

In [30]:
product = vec_multiply(u, v)
product

np.int64(228)

In [31]:
#vec_multiply(a, v) # AssertionError - diff vector dimensions

# use built-in Numpy function
u.dot(v)

np.int64(228)

In [32]:
# matrix - vector multiplication

big_u = np.random.randint(10, size=(3, 10))
big_u

array([[0, 4, 2, 4, 1, 7, 8, 2, 9, 8],
       [7, 1, 6, 8, 5, 9, 9, 9, 3, 0],
       [0, 2, 8, 8, 2, 9, 6, 5, 6, 6]])

In [33]:
v

array([6, 1, 3, 5, 8, 4, 6, 3, 9, 2])

In [34]:
big_u.dot(v)

array([217, 285, 235])

In [35]:
# or using our function - row by row

[vec_multiply(big_u[0], v), vec_multiply(big_u[1], v), vec_multiply(big_u[2], v)]

[np.int64(217), np.int64(285), np.int64(235)]

In [36]:
# matrix - matrix multiplication

big_v = np.random.randint(10, size=(10, 3))
big_v

array([[6, 3, 8],
       [2, 1, 4],
       [8, 1, 6],
       [9, 5, 1],
       [2, 4, 7],
       [6, 4, 5],
       [8, 3, 0],
       [0, 5, 7],
       [5, 0, 8],
       [6, 5, 1]])

In [37]:
X = big_u.dot(big_v)
X

array([[261, 132, 168],
       [315, 196, 271],
       [312, 167, 212]])

## Identity matrix

In [38]:
# if we multiply any matrix to identity matrix I we get this matrix back - similar to multiplication by 1

I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
I.dot(X)

array([[261., 132., 168.],
       [315., 196., 271.],
       [312., 167., 212.]])

In [40]:
X.dot(I)

array([[261., 132., 168.],
       [315., 196., 271.],
       [312., 167., 212.]])

In [41]:
big_v.dot(I)

array([[6., 3., 8.],
       [2., 1., 4.],
       [8., 1., 6.],
       [9., 5., 1.],
       [2., 4., 7.],
       [6., 4., 5.],
       [8., 3., 0.],
       [0., 5., 7.],
       [5., 0., 8.],
       [6., 5., 1.]])

In [42]:
# but !!!
# big_u.dot(I) # will give ValueError !!!

## Inverse matrix

In [43]:
# something like A * A**-1 = I means A**-1 is inverse of A

X

array([[261, 132, 168],
       [315, 196, 271],
       [312, 167, 212]])

In [44]:
inv_x = np.linalg.inv(X)
inv_x

array([[ 0.06500342, -0.00126322, -0.04989736],
       [-0.31180588, -0.05116059,  0.31249013],
       [ 0.14995526,  0.04216011, -0.16800884]])

In [45]:
# checking - -5.68121938e-17 is in fact zero....
X.dot(inv_x)

array([[ 1.00000000e+00, -1.05471187e-15,  0.00000000e+00],
       [ 2.30371278e-15,  1.00000000e+00, -3.10862447e-15],
       [ 3.66373598e-15, -9.71445147e-16,  1.00000000e+00]])

## Pandas data frames

In [46]:
# https://www.youtube.com/watch?v=0j3XK5PsnxA

import pandas as pd

In [47]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [48]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Series

In [49]:
df["Year"] # bracket notation

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [50]:
# even better so - dot notation works too!
# watch capital letters and avoid blank spaces in col names
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [51]:
df[['Make', 'Model', 'MSRP']] # we define a subset of columns to select

Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [52]:
# add a new column

df['id'] = [10, 20, 30, 40, 50]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000  10  
1         Sedan  27150  20  
2   convertible  54990  30  
3       4dr SUV  34450  40  
4        Pickup  32340  50

In [53]:
# and remove it
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Index

In [54]:
df.index # every dataframe have it by default - like a row number...

RangeIndex(start=0, stop=5, step=1)

In [55]:
# accessing rows via index
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [56]:
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [57]:
# we can replace index but we woud need a positional index iloc after

df.index = ['a', 'b','c','d','e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [58]:
df.iloc[1] # using positional index, as our normal index has been replaced

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [59]:
df.loc[['b','c']]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [60]:
# how to fix broken index

df = df.reset_index()
df

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

## Element-wise operations

In [61]:
df['Engine HP'] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [62]:
df.Year >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [63]:
# and use logical expressions to select rows
df[df.Year >= 2015]

index     Make     Model  Year  Engine HP  Engine Cylinders  \
1     b  Hyundai    Sonata  2017        NaN                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
1         AUTOMATIC         Sedan  27150  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

## String operators

In [64]:
df.Vehicle_Style.str.lower().str.replace(' ', '_')

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

In [65]:
df # this and many other operations like index are not in-place:

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [66]:
# how to make changes in-place - similar to index reset before
df.Vehicle_Style = df.Vehicle_Style.str.lower().str.replace(' ', '_')
df

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr_suv  34450  
4            MANUAL        pickup  32340

## Summarising operations

In [67]:
df.MSRP.min()

np.int64(2000)

In [68]:
df.MSRP.max()

np.int64(54990)

In [69]:
df.MSRP.mean()

np.float64(30186.0)

In [70]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [76]:
# or even better - rounded and converted floats to int
df.describe().round(0).astype(int)

Year  Engine HP  Engine Cylinders   MSRP
count     5          4                 5      5
mean   2010        203                 4  30186
std      11         51                 1  18985
min    1991        138                 4   2000
25%    2010        180                 4  27150
50%    2017        206                 4  32340
75%    2017        229                 4  34450
max    2017        261                 6  54990

In [78]:
df.nunique() # unique values - good for categorical variables

index                5
Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

## Missing values

In [80]:
df.isnull().sum()

index                0
Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

## Group by

In [83]:
# Group by - for example make 2 groups by transmission type - manual vs automatic

df.groupby('Transmission Type').MSRP.mean().round(2)

Transmission Type
AUTOMATIC    30800.00
MANUAL       29776.67
Name: MSRP, dtype: float64

## Getting Numpy arrays

In [84]:
df.MSRP.values # we got numpy array - array([ 2000, 27150, 54990, 34450, 32340])

array([ 2000, 27150, 54990, 34450, 32340])

In [85]:
df.to_dict(orient='records') # list all rows as records dictionaries

[{'index': 'a',
  'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'index': 'b',
  'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'index': 'c',
  'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'index': 'd',
  'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'index': 'e',
  'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 323