In [2]:
import numpy as np
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Create simple arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
# from python list
l = [1, 2, 3, 4, 5, 6, 10]
a = np.array(l)
a

array([ 1,  2,  3,  4,  5,  6, 10])

In [11]:
a[3] # accessing elements by indices

np.int64(4)