In [1]:
import numpy as np
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Create simple arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
# from python list
l = [1, 2, 3, 4, 5, 6, 10]
a = np.array(l)
a

array([ 1,  2,  3,  4,  5,  6, 10])

In [6]:
int(a[3]) # accessing elements by indices

4

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional arrays

In [10]:
n = np.zeros((5, 3)) # same way it can create arrays from multi-dimensional python lists...

In [12]:
# adressing row
n[1] = [1, 2, 3]
n

array([[0., 0., 0.],
       [1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# adressing column using : operator
n[:, 2] = [10]*5
n

array([[ 0.,  0., 10.],
       [ 1.,  2., 10.],
       [ 0.,  0., 10.],
       [ 0.,  0., 10.],
       [ 0.,  0., 10.]])

## Randomly generate arrays and random seeds

In [15]:
# if we don't need the seed - we get a new array every time
random_different_values = np.random.rand(5, 2)
random_different_values 
# array([[0.20303549, 0.49645129],
#        [0.98002669, 0.31447288],
#        [0.72151985, 0.1577254 ],
#        [0.67189464, 0.64356604],
#        [0.71482408, 0.81511062]])

# array([[0.18126911, 0.94628129],
#        [0.32282185, 0.18224532],
#        [0.28034724, 0.43799104],
#        [0.2495647 , 0.0891415 ],
#        [0.00137409, 0.93752768]])

# and so on - different each time

array([[0.18126911, 0.94628129],
       [0.32282185, 0.18224532],
       [0.28034724, 0.43799104],
       [0.2495647 , 0.0891415 ],
       [0.00137409, 0.93752768]])